spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distributorntwdb
    username: root
    password: system
  jpa:
    show-sql: true
    generate-ddl: false
network:
  businessType: wholesale
  locationType: local distributor-network-dev1

eureka:
  client:
   register-with-eureka: true
   fetch-registry: false
   service-url:
     defaultZone: http://localhost:9091/eureka



 