spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distributorntwdb
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
  
